### ISSUE TITLE
Лицензия и переиспользование

### ISSUE THREAD

**Issue by nobbynobbs** [worldofswift/test-laravel-php#1]
@gorloffslava, @worldofswift, добрый день!

Скажите пожалуйста, можем ли мы использовать ваш проект в качестве тестового задания для кандидата?

**Comment by worldofswift** [comment]
Да, это возможно. Авторство требуется указывать только, если Вы будете выкладывать его публично на каких-то сайтах или учебных материалах.

Будем рады узнать, что за компания решила использовать это :)

Единственное - мы очень давно не обновляли репозиторий. Хотим обновить летом с новыми заданиями и разбить по разным темам. 

Текущий уровень задания в репозитории - уверенный джун и начинающий миддл.

**Comment by nobbynobbs** [comment]
вряд ли вам что-то скажет название компании http://studio-tg.ru/

> Текущий уровень задания в репозитории - уверенный джун и начинающий миддл.

Сейчас нам больше и не надо ))

Спасибо за репозиторий.
